"use strict";
const {test}=require("node:test"),assert=require("node:assert/strict");
const navigation=require("../public/js/pages/delivery/navigation-engine");
function encode(points){let lastLat=0,lastLng=0,result="";const part=value=>{value=value<0?~(value<<1):value<<1;let out="";while(value>=0x20){out+=String.fromCharCode((0x20|(value&0x1f))+63);value>>=5;}return out+String.fromCharCode(value+63);};for(const p of points){const lat=Math.round(p.latitude*1e5),lng=Math.round(p.longitude*1e5);result+=part(lat-lastLat)+part(lng-lastLng);lastLat=lat;lastLng=lng;}return result;}
const p=(latitude,longitude)=>({latitude,longitude});
function route(){const a=p(-23.6600,-46.5500),b=p(-23.6600,-46.5490),c=p(-23.6590,-46.5490);return{tipoOrigem:"GPS_ENTREGADOR",origem:a,destino:c,duracao:"120s",etapas:[
    {instrucao:"Siga em frente",manobra:"STRAIGHT",distanciaMetros:100,duracao:"60s",polyline:encode([a,b])},
    {instrucao:"Vire à esquerda",manobra:"TURN_LEFT",distanciaMetros:100,duracao:"60s",polyline:encode([b,c])}
]};}
test("navegação avança por GPS real e calcula manobra, distância, tempo e velocidade",()=>{const engine=navigation.create(route()),now=Date.now();let result=engine.update({...p(-23.66,-46.5498),precisao_m:5,velocidade_mps:10,atualizado_em:new Date(now).toISOString()},now);assert.equal(result.state,"navigating");assert.equal(result.current.instrucao,"Siga em frente");assert.equal(result.next.instrucao,"Vire à esquerda");assert.ok(result.toNextMeters>0&&result.toNextMeters<100);assert.ok(result.remainingSeconds>0&&result.remainingSeconds<120);assert.equal(result.speedKmh,36);
    result=engine.update({...p(-23.6598,-46.549),precisao_m:5,velocidade_mps:null,atualizado_em:new Date(now+5000).toISOString()},now+5000);assert.equal(result.current.instrucao,"Vire à esquerda");assert.ok(result.speedKmh>0,"Estima velocidade quando o navegador não a fornece");});
test("navegação não orienta com GPS antigo ou impreciso e só recalcula após duas posições fora da rota",()=>{const now=Date.now(),engine=navigation.create(route());assert.equal(engine.update({...p(-23.66,-46.55),precisao_m:5,atualizado_em:new Date(now-20000).toISOString()},now).state,"stale");assert.equal(engine.update({...p(-23.66,-46.55),precisao_m:80,atualizado_em:new Date(now).toISOString()},now).state,"imprecise");let result=engine.update({...p(-23.67,-46.57),precisao_m:5,atualizado_em:new Date(now+1000).toISOString()},now+1000);assert.equal(result.recalculate,false);result=engine.update({...p(-23.67,-46.57),precisao_m:5,atualizado_em:new Date(now+6000).toISOString()},now+6000);assert.equal(result.recalculate,true);});
test("dados incompletos não viram instrução de navegação",()=>{assert.equal(navigation.create({tipoOrigem:"GPS_ENTREGADOR",etapas:[]}),null);assert.throws(()=>navigation.decode("abc"));});
